version: '3.9'

services:
  postgres_db_test:
    image: postgres:14-alpine
    container_name: user_db
    restart: always
    ports:
    - '8001:5432' # Won't work on 5432, as another postgres instance is installed locally 😭
    environment:
      POSTGRES_USER: ollama_user
      POSTGRES_PASSWORD: v6LU2ysixQqihxon
      POSTGRES_DB: user_db
    volumes:
    - user_db:/var/lib/postgresql/data

volumes:
  user_db:
    driver: local